### ISSUE TITLE
Contributing readme

### ISSUE THREAD

**Issue by deadbirdi** [anshumanv/evolutions-webapp#3]
I think it might be a good idea to create a `Contributing.md` file for the contributors. Just some rules and guidelines 😄

**Comment by anshumanv** [comment]
Right, let's get one !

**Comment by anshumanv** [comment]
Also add build & run guidelines in `README.md`

**Comment by deadbirdi** [comment]
Yes! I'll let you make the `CONTRIBUTING.md` file since it's your repo and I figured you have a way of doing things 😄. I think we should maybe move the current `README.md` (which is the default readme shipped with `create-react-app`) to a `REACT-README.md` file for example. Then put the build guidelines, run guidelines, and project information in `README.md`.

**Comment by anshumanv** [comment]
Oh I didn't know create-react-app ships a `readme.md` of it's own, thanks for letting me know !
The current readme has everything so let's finalize a readme when we finish this app.

>  since it's your repo and I figured you have a way of doing things 

nothing like that man 😅 , I'm also a learner so feel free to propose any changes you wish to have 😄 

So we just need a sweet `CONTRIBUTING.md` then.

**Comment by anshumanv** [comment]
Sorry, I assigned myself by mistake before 😥

**Comment by anshumanv** [comment]
Okay you assigned me, nevermind I'll get this done real quick

**Comment by ad-dan** [comment]
Lol,  bhai. Instead of copy pasting the entire create-react-app documentation, It would be better if we included just a link to the documentation.

**Comment by deadbirdi** [comment]
I don’t think anyone copied and pasted it. It generates with the CLI command. 

Zachary E Sohovich
Full Stack Web Developer
https://sneakycr0w.com
zach@sneakycr0w.com

**Comment by ad-dan** [comment]
My bad, I should have worded it better. The tool generates the readme but we must modify it to represent the documentation for the project instead of keeping the default one.

**Comment by anshumanv** [comment]
We will do so @ad-dan once the project is setup.
