### ISSUE TITLE
Setup a basic page for the webapp

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/evolutions-webapp#4]
Let's get started with creating a basic page and using the API, UI/UX modifications can be done as we proceed.

**Comment by collinsnji** [comment]
Cool!. I'll work in this. @anshumanv, @sneakycr0w, is it OK to assign this to myself?

**Comment by anshumanv** [comment]
Feel free to assign it to yourself if you need, and send a PR once done, others can collaborate or suggest changes in the PR itself.

**Comment by collinsnji** [comment]
@anshumanv @sneakycr0w please take a look at this screenshot: https://imgur.com/a/f3j3l
Let me know what you think before I commit :)

**Comment by anshumanv** [comment]
Woah !
Looks so amazing !
Infact i think that `Evolutions` in the middle can even be used as a Logo for this app.
Please add your reviews @sneakycr0w

**Comment by deadbirdi** [comment]
Wow that looks great @collinsnji! The only gripe I'd have (and it's super minor) is just maybe a little magnifying glass icon aligned to the right side of the input box. 😄

**Comment by anshumanv** [comment]
Right @sneakycr0w that will look appealing :mag_right: :smile: 
What say @collinsnji ?

**Comment by collinsnji** [comment]
Sure! I'll add that right away 😄

**Comment by anshumanv** [comment]
Awaiting for your PR @collinsnji once done :smiley:

**Comment by anshumanv** [comment]
btw made a gitter channel, follow up for any discussion https://gitter.im/evolutions-webapp/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link
