### ISSUE TITLE
Fix mobile view

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/evolutions-webapp#44]
Mobile view is really messed up right now, please write appropriate media queries to fix it.

**Comment by anshumanv** [comment]
@prithaupadhayay can you help?

**Comment by anshumanv** [comment]
@prithaupadhyay can you help?

**Comment by prithaupadhyay** [comment]
@anshumanv I will surely try and will send the PR soon.

**Comment by singhrohan62** [comment]
Hey @prithaupadhyay  are you still working on this issue? I am also interested on working on this issue:grinning:

**Comment by prithaupadhyay** [comment]
The issue has been solved a few days back. @singhrohan62

**Comment by singhrohan62** [comment]
Could you tell me the commit id for that @prithaupadhyay ?

**Comment by singhrohan62** [comment]
BTW its looking beautiful....great work :clap::clap::clap:

**Comment by anshumanv** [comment]
Fixed
