### ISSUE TITLE
Create ISSUE and PR templates

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/evolutions-webapp#6]
Issue and PR templates are a necessity. It ensures that people stick to the guidelines also makes it easy for reviewers to get their reviews done.

**Comment by anshumanv** [comment]
@sneakycr0w @collinsnji I have them ready (created for a separate repo), will it be alright if I add them ?

**Comment by deadbirdi** [comment]
Go for it

Zachary E Sohovich
Full Stack Web Developer
https://sneakycr0w.com
zach@sneakycr0w.com
